"""add_leads_table

Revision ID: 5675437f39c5
Revises: 5ef57f174990
Create Date: 2026-07-16 01:13:12.306715

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5675437f39c5"
down_revision: str | Sequence[str] | None = "5ef57f174990"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("whatsapp_number", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("consent", sa.Boolean(), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("study_level", sa.String(length=100), nullable=False),
        sa.Column("intended_major", sa.String(length=255), nullable=False),
        sa.Column("preferred_language", sa.String(length=100), nullable=False),
        sa.Column("max_budget", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("utm_source", sa.String(length=100), nullable=True),
        sa.Column("utm_medium", sa.String(length=100), nullable=True),
        sa.Column("utm_campaign", sa.String(length=100), nullable=True),
        sa.Column("referring_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("leads")
    # ### end Alembic commands ###
