"""initial

Revision ID: 5ef57f174990
Revises:
Create Date: 2026-07-13 23:45:05.546333

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ef57f174990"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("records_received", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_unchanged", sa.Integer(), nullable=False),
        sa.Column("records_deactivated", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "universities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portal_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country_name", sa.String(), nullable=True),
        sa.Column("city_name", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("source_hash", sa.String(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_universities_portal_id"), "universities", ["portal_id"], unique=True
    )
    op.create_table(
        "programs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portal_id", sa.Integer(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("years", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("language_name", sa.String(), nullable=True),
        sa.Column("faculty_name", sa.String(), nullable=True),
        sa.Column("degree_name", sa.String(), nullable=True),
        sa.Column("currency_name", sa.String(), nullable=True),
        sa.Column("campus_name", sa.String(), nullable=True),
        sa.Column("campus_address", sa.String(), nullable=True),
        sa.Column("deposit_fee", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("deposit_note", sa.String(), nullable=True),
        sa.Column("prep_school_fee", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("prep_school_note", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("source_hash", sa.String(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["university_id"], ["universities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_programs_portal_id"), "programs", ["portal_id"], unique=True
    )
    op.create_table(
        "program_fees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portal_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("semester", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("fees", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("discounted_fees", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("cash_fees", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("source_hash", sa.String(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["program_id"], ["programs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_program_fees_portal_id"), "program_fees", ["portal_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_program_fees_portal_id"), table_name="program_fees")
    op.drop_table("program_fees")
    op.drop_index(op.f("ix_programs_portal_id"), table_name="programs")
    op.drop_table("programs")
    op.drop_index(op.f("ix_universities_portal_id"), table_name="universities")
    op.drop_table("universities")
    op.drop_table("sync_runs")
    # ### end Alembic commands ###
