"""launch_readiness_milestone

Revision ID: a77ed89495de
Revises: 5675437f39c5
Create Date: 2026-07-16 01:51:56.461203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77ed89495de'
down_revision: Union[str, Sequence[str], None] = '5675437f39c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.add_column('leads', sa.Column('assessment_session_id', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('privacy_policy_version', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'leads', ['assessment_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='unique')
    op.drop_column('leads', 'privacy_policy_version')
    op.drop_column('leads', 'consent_timestamp')
    op.drop_column('leads', 'assessment_session_id')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
